title: TLDR.HackNews24
description: As the title said, read it 1000 years later bro.
theme: jekyll-theme-minimal
markdown: kramdown
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true

# GitHub Pages configuration
baseurl: "/tldr-hacknews-24" # This should match your repository name
url: "https://krabswong.github.io"

# Collections configuration
collections:
  posts:
    output: true
    permalink: "/tldr-hacknews-24/:year/:month/:day/"

# Defaults for posts
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
